# SPDX-FileCopyrightText: 2015 Eric Larson
#
# SPDX-License-Identifier: Apache-2.0

arch:
  - amd64
  - ppc64le

language: python
sudo: false


python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9-dev

install: pip install tox-travis

script: tox
